// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

// export default function Home() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>


//         <div className={styles.grid}>
          
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }


import { useState } from "react";
import axios from "axios";
// import styles from "../styles/globals.css";

const Home = () => {
  const [response, setResponse] = useState("Hallo! Ik ben Bob, uw digitale hulp voor het rekenmodel. Hoe kan ik u helpen?");
  const [value, setValue] = useState("");

  // Update state as user types in the input field
  const onChange = (e) => setValue(e.target.value);

  // Function that runs when the user presses the button
  const handleSubmit = async () => {
    const response = (await axios.post("/chat", { question: value })).data.choices[0].message.content;
    setResponse(response);
  };

  return (
    <div className="container">
      <div>
        <input type="text" value={value} onChange={onChange} />
      </div>
      <div>
        <button onClick={handleSubmit}>Send</button>
      </div>
      <div>
        <p>Chatbot: {response}</p>
      </div>
    </div>
  );
};

export default Home;

